name: instacechat
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_webview_plugin: ^0.3.4
  date_format: ^1.0.6
  cupertino_icons: ^0.1.2
  # 透明图片占位符
  transparent_image: ^1.0.0
  cached_network_image: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:

  #加载页面图片资源
  - images/loading.jpeg

  #底部tab切换图片资源
  - images/contact_list_normal.png
  - images/contact_list_pressed.png
  - images/profile_normal.png
  - images/profile_pressed.png
  - images/message_normal.png
  - images/message_pressed.png
  - images/icon_find_normal.png
  - images/icon_find_pressed.png

  #菜单按钮
  - images/icon_menu_addfriend.png
  - images/icon_menu_group.png
  - images/icon_menu_scan.png
  - images/icon_menu_help.png
  - images/icon_menu_tag.png
  - images/icon_menu_add.png
  - images/icon_menu_public.png
  #启动页
  - images/launch.jpg

  #右箭头
  - images/arrow_right.png
  #好友模块图标
  - images/icon_addfriend.png
  - images/icon_groupchat.png
  - images/icon_public.png

  
  #我的模块（微信图标）
  - images/yixiu.jpeg
  - images/icon_pay.png
  - images/icon_collect.png
  - images/icon_ablumn.png
  - images/icon_package.png
  - images/icon_emoji.png
  - images/icon_setting.png
  - images/QRcode.png


  #发现模块
  - images/friendCircle.png
  - images/icon_scan.png
  - images/icon_wave.png
  - images/icon_look.png
  - images/icon_search.png
  - images/icon_near.png
  - images/icon_float.png
  - images/icon_shopping.png
  - images/icon_game.png
  - images/icon_miniapp.png


















